#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Generator-vCard-RDF
version:      1.3
version_from: lib/XML/Generator/vCard/RDF.pm
installdirs:  site
requires:
    Encode:                        0
    Test::More:                    0
    Digest::SHA1:                  2.10
    Text::vCard:                   1.9
    XML::SAX:                      0.12
    Memoize:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
